### ISSUE TITLE
replace `/tmp/...` in output

### ISSUE THREAD

**Issue by jsoref** [perl6/evalbot#8]
1:21 PM P<psch> m: say <<# foo>>
1:21 PM C<+camelia> rakudo-moar 9cfcb9: OUTPUT«===SORRY!=== Error while compiling /tmp/wTXSi7ITxR␤Unable to parse expression in shell-quote words; couldn't find final '>>' ␤at /tmp/wTXSi7ITxR:1␤------> say <<# foo>>⏏<EOL>␤    expecting any of:␤        argument list␤        sh…»

could camelia replace `/tmp/..../` with `script`?
it eats too many chars from the output :(

**Comment by AlexDaniel** [comment]
Done. See https://github.com/perl6/evalbot/commit/282650f9d52ff9d42f7b7ea9109a7be9f47022ba and https://github.com/perl6/evalbot/commit/4ef2b5530e6e910732de59713d8c3e5bc0679864
